services:
    samiax_alo_tech_api.authentication:
        class: AloTech\Authentication
        calls:
            - [setUsername, [%samiax_alo_tech_api.username%]]
            - [setAppToken, [%samiax_alo_tech_api.app_token%]]

    samiax_alo_tech_api.alotech:
        class: AloTech\AloTech
        arguments:
            - '@samiax_alo_tech_api.authentication'
